variable subscription_id { }
variable tenant_id       { }
variable region          { }
variable resource_group  { }
variable cluster_name    { }
variable node_pool       { }
variable node_count      { }
variable vm_size         { }
variable tag             { }
variable client_id       { }
variable client_secret   { }
variable principal_id    { }
variable namespace       { }
